"""Criacao inicial das tabelas do SGC

Revision ID: dff2a095d294
Revises: 
Create Date: 2026-06-01 17:31:38.223202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dff2a095d294'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=18), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('whatsapp', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('endereco', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clientes_cpf_cnpj'), ['cpf_cnpj'], unique=True)
        batch_op.create_index(batch_op.f('ix_clientes_nome'), ['nome'], unique=False)

    op.create_table('produtos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_interno', sa.String(length=50), nullable=False),
    sa.Column('nome', sa.String(length=150), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('categoria', sa.String(length=50), nullable=True),
    sa.Column('preco_custo', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('preco_venda', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('quantidade_estoque', sa.Integer(), nullable=False),
    sa.Column('estoque_minimo', sa.Integer(), nullable=False),
    sa.Column('imagem_url', sa.String(length=255), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produtos_categoria'), ['categoria'], unique=False)
        batch_op.create_index(batch_op.f('ix_produtos_codigo_interno'), ['codigo_interno'], unique=True)
        batch_op.create_index(batch_op.f('ix_produtos_nome'), ['nome'], unique=False)

    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('nome_completo', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_usuarios_username'), ['username'], unique=True)

    op.create_table('caixas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_abertura', sa.DateTime(), nullable=False),
    sa.Column('data_fechamento', sa.DateTime(), nullable=True),
    sa.Column('saldo_inicial', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('saldo_final', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('total_vendas_dinheiro', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_vendas_pix', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_vendas_cartao', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_vendas_fiado', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('movimentacoes_estoque',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('data_movimentacao', sa.DateTime(), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movimentacoes_estoque_data_movimentacao'), ['data_movimentacao'], unique=False)

    op.create_table('vendas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('data_venda', sa.DateTime(), nullable=True),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendas_data_venda'), ['data_venda'], unique=False)

    op.create_table('itens_venda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('venda_id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.ForeignKeyConstraint(['venda_id'], ['vendas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_venda')
    with op.batch_alter_table('vendas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendas_data_venda'))

    op.drop_table('vendas')
    with op.batch_alter_table('movimentacoes_estoque', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movimentacoes_estoque_data_movimentacao'))

    op.drop_table('movimentacoes_estoque')
    op.drop_table('caixas')
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_usuarios_username'))

    op.drop_table('usuarios')
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produtos_nome'))
        batch_op.drop_index(batch_op.f('ix_produtos_codigo_interno'))
        batch_op.drop_index(batch_op.f('ix_produtos_categoria'))

    op.drop_table('produtos')
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clientes_nome'))
        batch_op.drop_index(batch_op.f('ix_clientes_cpf_cnpj'))

    op.drop_table('clientes')
    # ### end Alembic commands ###
